/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainLayoutRouteImport } from './routes/_mainLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainLayoutSelectRouteImport } from './routes/_mainLayout/select'
import { Route as MainLayoutResultRouteImport } from './routes/_mainLayout/result'
import { Route as MainLayoutMainRouteImport } from './routes/_mainLayout/main'
import { Route as DatingLayoutChar49548Char44060Char54021RouteImport } from './routes/_datingLayout/소개팅'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutSelectRoute = MainLayoutSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutResultRoute = MainLayoutResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutMainRoute = MainLayoutMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => MainLayoutRoute,
} as any)
const DatingLayoutChar49548Char44060Char54021Route =
  DatingLayoutChar49548Char44060Char54021RouteImport.update({
    id: '/_datingLayout/소개팅',
    path: '/소개팅',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/소개팅': typeof DatingLayoutChar49548Char44060Char54021Route
  '/main': typeof MainLayoutMainRoute
  '/result': typeof MainLayoutResultRoute
  '/select': typeof MainLayoutSelectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/소개팅': typeof DatingLayoutChar49548Char44060Char54021Route
  '/main': typeof MainLayoutMainRoute
  '/result': typeof MainLayoutResultRoute
  '/select': typeof MainLayoutSelectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/_datingLayout/소개팅': typeof DatingLayoutChar49548Char44060Char54021Route
  '/_mainLayout/main': typeof MainLayoutMainRoute
  '/_mainLayout/result': typeof MainLayoutResultRoute
  '/_mainLayout/select': typeof MainLayoutSelectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/소개팅' | '/main' | '/result' | '/select'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/소개팅' | '/main' | '/result' | '/select'
  id:
    | '__root__'
    | '/'
    | '/_mainLayout'
    | '/_datingLayout/소개팅'
    | '/_mainLayout/main'
    | '/_mainLayout/result'
    | '/_mainLayout/select'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  DatingLayoutChar49548Char44060Char54021Route: typeof DatingLayoutChar49548Char44060Char54021Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/select': {
      id: '/_mainLayout/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof MainLayoutSelectRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/result': {
      id: '/_mainLayout/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof MainLayoutResultRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/main': {
      id: '/_mainLayout/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainLayoutMainRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_datingLayout/소개팅': {
      id: '/_datingLayout/소개팅'
      path: '/소개팅'
      fullPath: '/소개팅'
      preLoaderRoute: typeof DatingLayoutChar49548Char44060Char54021RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainLayoutRouteChildren {
  MainLayoutMainRoute: typeof MainLayoutMainRoute
  MainLayoutResultRoute: typeof MainLayoutResultRoute
  MainLayoutSelectRoute: typeof MainLayoutSelectRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutMainRoute: MainLayoutMainRoute,
  MainLayoutResultRoute: MainLayoutResultRoute,
  MainLayoutSelectRoute: MainLayoutSelectRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainLayoutRoute: MainLayoutRouteWithChildren,
  DatingLayoutChar49548Char44060Char54021Route:
    DatingLayoutChar49548Char44060Char54021Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
